
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc_test
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: non-null
  jpa:
    hibernate:
      ddl-auto: create


server:
  port: 8000
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
